### ISSUE TITLE
[Enchangement] CR - PP 19/11/21

### ISSUE THREAD

**Issue by Eckybrazzz** [mauriciomonta/web_portfolio#15]
# :wave: @mauriciomonta  :recycle: 

Your Js code looks awesome. The only issue that I could find is some code that is commented out and that code should be removed to keep your Js clean and readable.

Please find the part below 

```const mailInput = document.getElementById('email');

/* const nameInput = document.getElementById('name');
const surnameInput = document.getElementById('surname');
const messageInput = document.getElementById('message-area');
*/

let canSubmit = Boolean;
```

Happy coding!

**Comment by mauriciomonta** [comment]
@Eckybrazzz Thanks for that observation. I'll remove that lines!
